// <auto-generated />
using System;
using DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(BradescoApiDbContext))]
    [Migration("20230501092905_ApiQueries Control Added")]
    partial class ApiQueriesControlAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataAccess.Model.VehicleApiQueryHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("MaxEffectiness")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("MinEffectiness")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("QueryDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ApiQueryHistories");
                });

            modelBuilder.Entity("DataAccess.Model.VehicleModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BradescoApiCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FipeCod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GasCod")
                        .HasColumnType("int");

                    b.Property<string>("GasKind")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GearCod")
                        .HasColumnType("int");

                    b.Property<string>("GearMode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GroupCod")
                        .HasColumnType("int");

                    b.Property<int>("KindCod")
                        .HasColumnType("int");

                    b.Property<string>("Manufactur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ManufacturCod")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("QueryHistoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VehicleGroup")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleKind")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("QueryHistoryId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("DataAccess.Model.YearInfoModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Effectiveness")
                        .HasColumnType("datetime2");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.Property<Guid?>("VehicleModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VehicleModelId");

                    b.ToTable("Years");
                });

            modelBuilder.Entity("DataAccess.Model.VehicleModel", b =>
                {
                    b.HasOne("DataAccess.Model.VehicleApiQueryHistory", "QueryHistory")
                        .WithMany("VehicleModels")
                        .HasForeignKey("QueryHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QueryHistory");
                });

            modelBuilder.Entity("DataAccess.Model.YearInfoModel", b =>
                {
                    b.HasOne("DataAccess.Model.VehicleModel", "VehicleModel")
                        .WithMany("Years")
                        .HasForeignKey("VehicleModelId");

                    b.Navigation("VehicleModel");
                });

            modelBuilder.Entity("DataAccess.Model.VehicleApiQueryHistory", b =>
                {
                    b.Navigation("VehicleModels");
                });

            modelBuilder.Entity("DataAccess.Model.VehicleModel", b =>
                {
                    b.Navigation("Years");
                });
#pragma warning restore 612, 618
        }
    }
}
